window.speakers = {
  'alberto': [
    'echoes-0.wav',
    'echoes-4.wav',
    'echoes-24.wav',
    'echoes-25.wav',
    'echoes-26.wav',
    'echoes-40.wav',
    'echoes-41.wav',
    'echoes-42.wav',
    'echoes-54.wav',
    'echoes-79.wav',
    'echoes-86.wav',
  ],
  'qianxun': [
    'echoes-2.wav',
    'echoes-29.wav',
    'echoes-30.wav',
  ],
  'nilya': [
    'echoes-1.wav',
    'echoes-28.wav',
    'echoes-47.wav',
    'echoes-62.wav',
  ],
  'rouxi': [
    'echoes-3.wav',
    'echoes-5.wav',
    'echoes-6.wav',
  ],
  'hem': [
    'echoes-18.wav',
    'echoes-22.wav',
    'echoes-23.wav',
  ],
  'antonio': [
    'echoes-19.wav',
    'echoes-20.wav',
    'echoes-21.wav',
    'echoes-27.wav',
    'echoes-45.wav',
    'echoes-46.wav',
    'echoes-80.wav',
    'echoes-81.wav',
  ],
  'kazuki': [
    'echoes-7.wav',
    'echoes-8.wav',
    'echoes-9.wav',
    'echoes-10.wav',
    'echoes-11.wav',
    'echoes-12.wav',
    'echoes-13.wav',
    'echoes-14.wav',
    'echoes-15.wav',
    'echoes-16.wav',
    'echoes-17.wav',
    'echoes-82.wav',
    'echoes-83.wav',
    'echoes-84.wav',
    'echoes-85.wav',
  ],
  'chihim': [
    'echoes-31.wav',
    'echoes-32.wav',
    'echoes-33.wav',
    'echoes-34.wav',
    'echoes-77.wav',
    'echoes-78.wav',
  ],
  'sangbong': [
    'echoes-35.wav',
    'echoes-36.wav',
    'echoes-37.wav',
    'echoes-38.wav',
    'echoes-39.wav',
  ],
  'josh': [
    'echoes-43.wav',
    'echoes-44.wav',
    'echoes-60.wav',
    'echoes-61.wav',
  ],
  'bojana': [
    'echoes-48.wav',
    'echoes-49.wav',
    'echoes-50.wav',
    'echoes-51.wav',
    'echoes-52.wav',
  ],
  'soumya': [
    'echoes-53.wav'
  ],
  'victor': [
    'echoes-55.wav',
    'echoes-56.wav',
    'echoes-57.wav',
    'echoes-58.wav',
    'echoes-59.wav',
  ],
  'deba': [
    'echoes-63.wav',
    'echoes-65.wav',
  ],
  'julia': [
    'echoes-64.wav',
    'echoes-66.wav',
  ],
  "ayse": [
    'echoes-67.wav',
    'echoes-68.wav',
    'echoes-69.wav',
    'echoes-70.wav',
    'echoes-71.wav',
    'echoes-72.wav',
    'echoes-73.wav',
    'echoes-74.wav',
    'echoes-75.wav',
    'echoes-76.wav',
  ],
  'hanna': [
    'echoes-87.wav',
    'echoes-88.wav',
    'echoes-89.wav',
  ]
}
